$center-float-large = ^(center-float-large)$|^(.*Geeqie.*)$|^(.*geeqie.*)$|^(.*celluloid.*)$|^(.*mpv.*)$|^(.*File Upload.*)$|^(.*imv.*)$

windowrule {
  name = center-float-large
  float = on
  size = (monitor_w*0.7) (monitor_h*0.7)
  center = 1
  match:class = $center-float-large
}


$center-float = ^(center-float)$|^(.*file-roller.*)$|^(.*FileRoller.*)$|^(.*blueman-manager.*)$|^(.*blueberry.py.*)$
$center-float-title = ^(.*Open Folder.*)$|^(.*Open File.*)$|^(.*Save File.*)$|^(.*Save Folder.*)$|^(.*Save Image.*)$|^(.*Library.*)$|^(.*Save As.*)$|^(.*Open As.*)$|^(.*Volume Control.*)$|^(.*Settings.*)$|^(.*Warning.*)$|^(.*nmtui.*)$|^(update.sh)$
windowrule {
  name = center-float
  float = on
  size = (monitor_w*0.5) (monitor_h*0.5)
  center = 1
  match:class = $center-float
}

windowrule {
  name = center-float-title
  float = on
  size = (monitor_w*0.5) (monitor_h*0.5)
  center = 1
  match:title = $center-float-title
}


$center-float-mini = ^(center-float-mini)$|^(.*galculator.*)$|^(.*ytdlp-gui.*)$
windowrule {
  name = center-float-mini
  float = on
  size = (monitor_w*0.3) (monitor_h*0.4)
  center = 1
  match:class = $center-float-mini
}


windowrule {
  name = windowrule-5
  suppress_event = maximize
  match:class = .*
}

windowrule {
  name = windowrule-6
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}

windowrule {
  name = windowrule-7
  float = on
  opacity = 1 1
  idle_inhibit = fullscreen
  match:class = steam
}

windowrule {
  name = windowrule-8
  center = on
  size = 1100 700
  match:class = steam
  match:title = Steam
}

windowrule {
  name = windowrule-9
  size = 460 800
  match:class = steam
  match:title = Friends List
}


windowrule {
  name = windowrule-10
  workspace = 2
  match:class = firefox
}

windowrule {
  name = windowrule-11
  workspace = 3
  match:class = discord
}


layerrule {
  name = layerrule-1
  blur = on
  ignore_alpha = 0.1
  match:namespace = swaync-control-center
}

layerrule {
  name = layerrule-2
  blur = on
  ignore_alpha = 0.1
  match:namespace = swaync-notification-window
}

