exec-once = uwsm-app -- swaybg -i ~/Pictures/current/current.png -m fill
exec-once = uwsm-app -- swaync
exec-once = uwsm-app -- waybar
exec-once = uwsm-app -- wl-paste --watch cliphist store
exec-once = sh /home/winter/.config/hypr/scripts/monitor-attached.sh
