monitor=eDP-1,2880x1920@120.00,auto,2.00

bindl=,switch:off:Lid Switch,exec,/home/winter/.config/hypr/scripts/lid.sh open
bindl=,switch:on:Lid Switch,exec,/home/winter/.config/hypr/scripts/lid.sh close
